import {
  DESCRIPTION_MAX_LENGTH,
  TASK_STATUSES,
  TITLE_MAX_LENGTH,
  isTaskStatus,
  type TaskStatus,
} from '../../shared/task';

/** The editable fields of a task after validation, with defaults filled in. */
export interface ValidTaskInput {
  title: string;
  description: string;
  status: TaskStatus;
  dueDate: string | null;
}

export type ValidationResult<T> = { ok: true; value: T } | { ok: false; message: string };

const ALLOWED_FIELDS = new Set(['title', 'description', 'status', 'dueDate']);
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const DATE_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/**
 * Validates the body of POST /tasks and PUT /tasks/{id}.
 * PUT is a full replacement, so both use the same rules: omitted optional
 * fields fall back to their defaults.
 */
export function parseTaskInput(rawBody: string | null): ValidationResult<ValidTaskInput> {
  if (!rawBody) {
    return fail('Request body is required');
  }

  let body: unknown;
  try {
    body = JSON.parse(rawBody);
  } catch {
    return fail('Request body must be valid JSON');
  }

  if (typeof body !== 'object' || body === null || Array.isArray(body)) {
    return fail('Request body must be a JSON object');
  }

  const fields = body as Record<string, unknown>;

  const unknownField = Object.keys(fields).find((key) => !ALLOWED_FIELDS.has(key));
  if (unknownField) {
    return fail(`Unknown field: ${unknownField}`);
  }

  const { title, description = '', status = 'TODO', dueDate = null } = fields;

  if (typeof title !== 'string' || title.trim() === '') {
    return fail('title is required and must be a non-empty string');
  }
  if (title.trim().length > TITLE_MAX_LENGTH) {
    return fail(`title must be at most ${TITLE_MAX_LENGTH} characters`);
  }

  if (typeof description !== 'string') {
    return fail('description must be a string');
  }
  if (description.trim().length > DESCRIPTION_MAX_LENGTH) {
    return fail(`description must be at most ${DESCRIPTION_MAX_LENGTH} characters`);
  }

  if (!isTaskStatus(status)) {
    return fail(`status must be one of: ${TASK_STATUSES.join(', ')}`);
  }

  if (dueDate !== null && !isValidDate(dueDate)) {
    return fail('dueDate must be a valid date in YYYY-MM-DD format, or null');
  }

  return {
    ok: true,
    value: { title: title.trim(), description: description.trim(), status, dueDate },
  };
}

/** Validates the optional ?status= query parameter of GET /tasks. */
export function parseStatusFilter(value: string | undefined): ValidationResult<TaskStatus | undefined> {
  if (value === undefined || value === '') {
    return { ok: true, value: undefined };
  }
  if (!isTaskStatus(value)) {
    return fail(`status must be one of: ${TASK_STATUSES.join(', ')}`);
  }
  return { ok: true, value };
}

/** Task ids are UUIDs generated by the server. */
export function isValidTaskId(id: string | undefined): id is string {
  return typeof id === 'string' && UUID_PATTERN.test(id);
}

function isValidDate(value: unknown): value is string {
  if (typeof value !== 'string' || !DATE_PATTERN.test(value)) {
    return false;
  }
  // Rejects impossible dates like 2026-02-30 that still match the pattern.
  const date = new Date(`${value}T00:00:00Z`);
  return !Number.isNaN(date.getTime()) && date.toISOString().startsWith(value);
}

function fail(message: string): { ok: false; message: string } {
  return { ok: false, message };
}
